### ISSUE TITLE
Figure out how to automate labels and custom fields for priority and difficulty. Then automate a way to keep track of future labels/fields that show options.

### ISSUE THREAD

**Issue by denqiu** [denqiu/socket-io-monorepo#22]
Might remove single select fields. Figured out you can show/hide labels in board by going to view details and selecting Fields item.

- [x] Removed single select fields and enabled labels. 

Ref on automating labels and custom fields. Not needed anymore: https://github.com/denqiu/socket-io-monorepo/issues/22#issuecomment-2555977500

**Comment by denqiu** [comment]
<h1>Setup GitHub Actions Workflow (Generated by Perplexity AI)</h1>

Given that the workflow is intended to be generic and applicable to any GitHub repository, regardless of the project's language, using Python can be a good choice. Here’s how you can set up a GitHub Actions workflow using Python to sync labels and single select fields:

### Step 1: Create the Workflow File

Create a new file in your repository's `.github/workflows` directory, e.g., `.github/workflows/sync-labels-and-fields.yml`.

```yaml
name: Sync Labels and Single Select Fields

on:
  issues:
    types: [labeled, unlabeled]
  project_v2_item:
    types: [updated]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pygithub

      - name: Sync labels and single select fields
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          python sync.py
```

### Step 2: Create the `sync.py` Script

Create a new file named `sync.py` in the root of your repository. This script will handle the logic for syncing labels and single select fields.

```python
import os
from github import Github

def get_issue_labels(g, issue_number):
    issue = g.get_repo(os.getenv('REPO_NAME')).get_issue(issue_number)
    return [label.name for label in issue.labels]

def get_project_item_field(g, issue_number, field_name):
    # This part assumes you know the project ID and the field ID.
    # You may need to adjust this to fetch the project and field IDs dynamically.
    project_id = 'YOUR_PROJECT_ID_HERE'
    project = g.get_project(project_id)
    cards = project.get_cards()
    for card in cards:
        if card.content_id == issue_number and card.content_type == 'Issue':
            field_values = card.get_field_values()
            for field_value in field_values:
                if field_value.field.name == field_name:
                    return field_value.value
    return None

def update_project_item_field(g, issue_number, field_name, value):
    # This part assumes you know the project ID and the field ID.
    # You may need to adjust this to fetch the project and field IDs dynamically.
    project_id = 'YOUR_PROJECT_ID_HERE'
    project = g.get_project(project_id)
    cards = project.get_cards()
    for card in cards:
        if card.content_id == issue_number and card.content_type == 'Issue':
            # Update the field value
            # Note: This is a simplified example and may need adjustments based on your specific setup.
            print(f"Updating {field_name} to {value}")
            # Here you would use the GitHub API to update the field value.
            # For simplicity, this example just prints the update.

def add_label(g, issue_number, label_name):
    issue = g.get_repo(os.getenv('REPO_NAME')).get_issue(issue_number)
    issue.add_to_labels(label_name)

def remove_label(g, issue_number, label_name):
    issue = g.get_repo(os.getenv('REPO_NAME')).get_issue(issue_number)
    issue.remove_from_labels(label_name)

def main():
    g = Github(os.getenv('GITHUB_TOKEN'))
    issue_number = int(os.getenv('ISSUE_NUMBER'))
    labels = get_issue_labels(g, issue_number)
    priority_field = get_project_item_field(g, issue_number, 'Priority')

    if 'high-priority' in labels:
        update_project_item_field(g, issue_number, 'Priority', 'High')
    elif 'medium-priority' in labels:
        update_project_item_field(g, issue_number, 'Priority', 'Medium')
    elif 'low-priority' in labels:
        update_project_item_field(g, issue_number, 'Priority', 'Low')

    if priority_field == 'High' and 'high-priority' not in labels:
        add_label(g, issue_number, 'high-priority')
    if priority_field == 'Medium' and 'medium-priority' not in labels:
        add_label(g, issue_number, 'medium-priority')
    if priority_field == 'Low' and 'low-priority' not in labels:
        add_label(g, issue_number, 'low-priority')

    if priority_field != 'High' and 'high-priority' in labels:
        remove_label(g, issue_number, 'high-priority')
    if priority_field != 'Medium' and 'medium-priority' in labels:
        remove_label(g, issue_number, 'medium-priority')
    if priority_field != 'Low' and 'low-priority' in labels:
        remove_label(g, issue_number, 'low-priority')

if __name__ == "__main__":
    main()
```

### Explanation

- **Workflow File**: The `.yml` file defines the workflow and triggers it on issue labeling/unlabeling and project item updates.
- **Python Script**: The `sync.py` script uses the `pygithub` library to interact with the GitHub API. It fetches issue labels, project item fields, and updates them accordingly.
- **Functions**: The script includes functions to get issue labels, get project item fields, update project item fields, add labels, and remove labels.

### Note

- You need to replace `'YOUR_PROJECT_ID_HERE'` with the actual ID of your GitHub Project.
- This example assumes you have the necessary permissions and tokens set up correctly.
- The `update_project_item_field` function is simplified and does not actually update the field value. You would need to use the GitHub API to perform this update, which might involve additional steps or using a different library.

This approach keeps the workflow generic and applicable to any GitHub repository, regardless of the project's language.
